// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/changelogtag"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
)

// ChangelogTag is the model entity for the ChangelogTag schema.
type ChangelogTag struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Color holds the value of the "color" field.
	Color string `json:"color,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChangelogTagQuery when eager-loading is set.
	Edges                ChangelogTagEdges `json:"edges"`
	group_changelog_tags *uuid.UUID
	selectValues         sql.SelectValues
}

// ChangelogTagEdges holds the relations/edges for other nodes in the graph.
type ChangelogTagEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// Changelogs holds the value of the changelogs edge.
	Changelogs []*Changelog `json:"changelogs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChangelogTagEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// ChangelogsOrErr returns the Changelogs value or an error if the edge
// was not loaded in eager-loading.
func (e ChangelogTagEdges) ChangelogsOrErr() ([]*Changelog, error) {
	if e.loadedTypes[1] {
		return e.Changelogs, nil
	}
	return nil, &NotLoadedError{edge: "changelogs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChangelogTag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case changelogtag.FieldName, changelogtag.FieldColor:
			values[i] = new(sql.NullString)
		case changelogtag.FieldCreatedAt, changelogtag.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case changelogtag.FieldID:
			values[i] = new(uuid.UUID)
		case changelogtag.ForeignKeys[0]: // group_changelog_tags
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChangelogTag fields.
func (_m *ChangelogTag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case changelogtag.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case changelogtag.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case changelogtag.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case changelogtag.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case changelogtag.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = value.String
			}
		case changelogtag.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field group_changelog_tags", values[i])
			} else if value.Valid {
				_m.group_changelog_tags = new(uuid.UUID)
				*_m.group_changelog_tags = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChangelogTag.
// This includes values selected through modifiers, order, etc.
func (_m *ChangelogTag) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the ChangelogTag entity.
func (_m *ChangelogTag) QueryGroup() *GroupQuery {
	return NewChangelogTagClient(_m.config).QueryGroup(_m)
}

// QueryChangelogs queries the "changelogs" edge of the ChangelogTag entity.
func (_m *ChangelogTag) QueryChangelogs() *ChangelogQuery {
	return NewChangelogTagClient(_m.config).QueryChangelogs(_m)
}

// Update returns a builder for updating this ChangelogTag.
// Note that you need to call ChangelogTag.Unwrap() before calling this method if this ChangelogTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChangelogTag) Update() *ChangelogTagUpdateOne {
	return NewChangelogTagClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChangelogTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChangelogTag) Unwrap() *ChangelogTag {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChangelogTag is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChangelogTag) String() string {
	var builder strings.Builder
	builder.WriteString("ChangelogTag(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("color=")
	builder.WriteString(_m.Color)
	builder.WriteByte(')')
	return builder.String()
}

// ChangelogTags is a parsable slice of ChangelogTag.
type ChangelogTags []*ChangelogTag
