// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/changelog"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ChangelogUpdate is the builder for updating Changelog entities.
type ChangelogUpdate struct {
	config
	hooks    []Hook
	mutation *ChangelogMutation
}

// Where appends a list predicates to the ChangelogUpdate builder.
func (_u *ChangelogUpdate) Where(ps ...predicate.Changelog) *ChangelogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChangelogUpdate) SetUpdatedAt(v time.Time) *ChangelogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *ChangelogUpdate) SetEntityID(v uuid.UUID) *ChangelogUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *ChangelogUpdate) SetNillableEntityID(v *uuid.UUID) *ChangelogUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ChangelogUpdate) SetSummary(v string) *ChangelogUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ChangelogUpdate) SetNillableSummary(v *string) *ChangelogUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_u *ChangelogUpdate) SetEntity(v *Entity) *ChangelogUpdate {
	return _u.SetEntityID(v.ID)
}

// Mutation returns the ChangelogMutation object of the builder.
func (_u *ChangelogUpdate) Mutation() *ChangelogMutation {
	return _u.mutation
}

// ClearEntity clears the "entity" edge to the Entity entity.
func (_u *ChangelogUpdate) ClearEntity() *ChangelogUpdate {
	_u.mutation.ClearEntity()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChangelogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChangelogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChangelogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChangelogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChangelogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := changelog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChangelogUpdate) check() error {
	if v, ok := _u.mutation.Summary(); ok {
		if err := changelog.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Changelog.summary": %w`, err)}
		}
	}
	if _u.mutation.EntityCleared() && len(_u.mutation.EntityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Changelog.entity"`)
	}
	return nil
}

func (_u *ChangelogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(changelog.Table, changelog.Columns, sqlgraph.NewFieldSpec(changelog.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(changelog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(changelog.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.EntityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   changelog.EntityTable,
			Columns: []string{changelog.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   changelog.EntityTable,
			Columns: []string{changelog.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{changelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChangelogUpdateOne is the builder for updating a single Changelog entity.
type ChangelogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChangelogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChangelogUpdateOne) SetUpdatedAt(v time.Time) *ChangelogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *ChangelogUpdateOne) SetEntityID(v uuid.UUID) *ChangelogUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *ChangelogUpdateOne) SetNillableEntityID(v *uuid.UUID) *ChangelogUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ChangelogUpdateOne) SetSummary(v string) *ChangelogUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ChangelogUpdateOne) SetNillableSummary(v *string) *ChangelogUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetEntity sets the "entity" edge to the Entity entity.
func (_u *ChangelogUpdateOne) SetEntity(v *Entity) *ChangelogUpdateOne {
	return _u.SetEntityID(v.ID)
}

// Mutation returns the ChangelogMutation object of the builder.
func (_u *ChangelogUpdateOne) Mutation() *ChangelogMutation {
	return _u.mutation
}

// ClearEntity clears the "entity" edge to the Entity entity.
func (_u *ChangelogUpdateOne) ClearEntity() *ChangelogUpdateOne {
	_u.mutation.ClearEntity()
	return _u
}

// Where appends a list predicates to the ChangelogUpdate builder.
func (_u *ChangelogUpdateOne) Where(ps ...predicate.Changelog) *ChangelogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChangelogUpdateOne) Select(field string, fields ...string) *ChangelogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Changelog entity.
func (_u *ChangelogUpdateOne) Save(ctx context.Context) (*Changelog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChangelogUpdateOne) SaveX(ctx context.Context) *Changelog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChangelogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChangelogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChangelogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := changelog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChangelogUpdateOne) check() error {
	if v, ok := _u.mutation.Summary(); ok {
		if err := changelog.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Changelog.summary": %w`, err)}
		}
	}
	if _u.mutation.EntityCleared() && len(_u.mutation.EntityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Changelog.entity"`)
	}
	return nil
}

func (_u *ChangelogUpdateOne) sqlSave(ctx context.Context) (_node *Changelog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(changelog.Table, changelog.Columns, sqlgraph.NewFieldSpec(changelog.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Changelog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, changelog.FieldID)
		for _, f := range fields {
			if !changelog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != changelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(changelog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(changelog.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.EntityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   changelog.EntityTable,
			Columns: []string{changelog.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   changelog.EntityTable,
			Columns: []string{changelog.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Changelog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{changelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
