// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/changelog"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/changelogtag"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ChangelogTagUpdate is the builder for updating ChangelogTag entities.
type ChangelogTagUpdate struct {
	config
	hooks    []Hook
	mutation *ChangelogTagMutation
}

// Where appends a list predicates to the ChangelogTagUpdate builder.
func (_u *ChangelogTagUpdate) Where(ps ...predicate.ChangelogTag) *ChangelogTagUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChangelogTagUpdate) SetUpdatedAt(v time.Time) *ChangelogTagUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ChangelogTagUpdate) SetName(v string) *ChangelogTagUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChangelogTagUpdate) SetNillableName(v *string) *ChangelogTagUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *ChangelogTagUpdate) SetColor(v string) *ChangelogTagUpdate {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *ChangelogTagUpdate) SetNillableColor(v *string) *ChangelogTagUpdate {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// ClearColor clears the value of the "color" field.
func (_u *ChangelogTagUpdate) ClearColor() *ChangelogTagUpdate {
	_u.mutation.ClearColor()
	return _u
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (_u *ChangelogTagUpdate) SetGroupID(id uuid.UUID) *ChangelogTagUpdate {
	_u.mutation.SetGroupID(id)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *ChangelogTagUpdate) SetGroup(v *Group) *ChangelogTagUpdate {
	return _u.SetGroupID(v.ID)
}

// AddChangelogIDs adds the "changelogs" edge to the Changelog entity by IDs.
func (_u *ChangelogTagUpdate) AddChangelogIDs(ids ...uuid.UUID) *ChangelogTagUpdate {
	_u.mutation.AddChangelogIDs(ids...)
	return _u
}

// AddChangelogs adds the "changelogs" edges to the Changelog entity.
func (_u *ChangelogTagUpdate) AddChangelogs(v ...*Changelog) *ChangelogTagUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChangelogIDs(ids...)
}

// Mutation returns the ChangelogTagMutation object of the builder.
func (_u *ChangelogTagUpdate) Mutation() *ChangelogTagMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *ChangelogTagUpdate) ClearGroup() *ChangelogTagUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearChangelogs clears all "changelogs" edges to the Changelog entity.
func (_u *ChangelogTagUpdate) ClearChangelogs() *ChangelogTagUpdate {
	_u.mutation.ClearChangelogs()
	return _u
}

// RemoveChangelogIDs removes the "changelogs" edge to Changelog entities by IDs.
func (_u *ChangelogTagUpdate) RemoveChangelogIDs(ids ...uuid.UUID) *ChangelogTagUpdate {
	_u.mutation.RemoveChangelogIDs(ids...)
	return _u
}

// RemoveChangelogs removes "changelogs" edges to Changelog entities.
func (_u *ChangelogTagUpdate) RemoveChangelogs(v ...*Changelog) *ChangelogTagUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChangelogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChangelogTagUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChangelogTagUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChangelogTagUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChangelogTagUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChangelogTagUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := changelogtag.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChangelogTagUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := changelogtag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChangelogTag.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := changelogtag.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "ChangelogTag.color": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChangelogTag.group"`)
	}
	return nil
}

func (_u *ChangelogTagUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(changelogtag.Table, changelogtag.Columns, sqlgraph.NewFieldSpec(changelogtag.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(changelogtag.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(changelogtag.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(changelogtag.FieldColor, field.TypeString, value)
	}
	if _u.mutation.ColorCleared() {
		_spec.ClearField(changelogtag.FieldColor, field.TypeString)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   changelogtag.GroupTable,
			Columns: []string{changelogtag.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   changelogtag.GroupTable,
			Columns: []string{changelogtag.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangelogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   changelogtag.ChangelogsTable,
			Columns: []string{changelogtag.ChangelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changelog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChangelogsIDs(); len(nodes) > 0 && !_u.mutation.ChangelogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   changelogtag.ChangelogsTable,
			Columns: []string{changelogtag.ChangelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changelog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangelogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   changelogtag.ChangelogsTable,
			Columns: []string{changelogtag.ChangelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changelog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{changelogtag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChangelogTagUpdateOne is the builder for updating a single ChangelogTag entity.
type ChangelogTagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChangelogTagMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChangelogTagUpdateOne) SetUpdatedAt(v time.Time) *ChangelogTagUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ChangelogTagUpdateOne) SetName(v string) *ChangelogTagUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChangelogTagUpdateOne) SetNillableName(v *string) *ChangelogTagUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *ChangelogTagUpdateOne) SetColor(v string) *ChangelogTagUpdateOne {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *ChangelogTagUpdateOne) SetNillableColor(v *string) *ChangelogTagUpdateOne {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// ClearColor clears the value of the "color" field.
func (_u *ChangelogTagUpdateOne) ClearColor() *ChangelogTagUpdateOne {
	_u.mutation.ClearColor()
	return _u
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (_u *ChangelogTagUpdateOne) SetGroupID(id uuid.UUID) *ChangelogTagUpdateOne {
	_u.mutation.SetGroupID(id)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *ChangelogTagUpdateOne) SetGroup(v *Group) *ChangelogTagUpdateOne {
	return _u.SetGroupID(v.ID)
}

// AddChangelogIDs adds the "changelogs" edge to the Changelog entity by IDs.
func (_u *ChangelogTagUpdateOne) AddChangelogIDs(ids ...uuid.UUID) *ChangelogTagUpdateOne {
	_u.mutation.AddChangelogIDs(ids...)
	return _u
}

// AddChangelogs adds the "changelogs" edges to the Changelog entity.
func (_u *ChangelogTagUpdateOne) AddChangelogs(v ...*Changelog) *ChangelogTagUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChangelogIDs(ids...)
}

// Mutation returns the ChangelogTagMutation object of the builder.
func (_u *ChangelogTagUpdateOne) Mutation() *ChangelogTagMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *ChangelogTagUpdateOne) ClearGroup() *ChangelogTagUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearChangelogs clears all "changelogs" edges to the Changelog entity.
func (_u *ChangelogTagUpdateOne) ClearChangelogs() *ChangelogTagUpdateOne {
	_u.mutation.ClearChangelogs()
	return _u
}

// RemoveChangelogIDs removes the "changelogs" edge to Changelog entities by IDs.
func (_u *ChangelogTagUpdateOne) RemoveChangelogIDs(ids ...uuid.UUID) *ChangelogTagUpdateOne {
	_u.mutation.RemoveChangelogIDs(ids...)
	return _u
}

// RemoveChangelogs removes "changelogs" edges to Changelog entities.
func (_u *ChangelogTagUpdateOne) RemoveChangelogs(v ...*Changelog) *ChangelogTagUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChangelogIDs(ids...)
}

// Where appends a list predicates to the ChangelogTagUpdate builder.
func (_u *ChangelogTagUpdateOne) Where(ps ...predicate.ChangelogTag) *ChangelogTagUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChangelogTagUpdateOne) Select(field string, fields ...string) *ChangelogTagUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChangelogTag entity.
func (_u *ChangelogTagUpdateOne) Save(ctx context.Context) (*ChangelogTag, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChangelogTagUpdateOne) SaveX(ctx context.Context) *ChangelogTag {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChangelogTagUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChangelogTagUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChangelogTagUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := changelogtag.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChangelogTagUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := changelogtag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChangelogTag.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := changelogtag.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "ChangelogTag.color": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChangelogTag.group"`)
	}
	return nil
}

func (_u *ChangelogTagUpdateOne) sqlSave(ctx context.Context) (_node *ChangelogTag, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(changelogtag.Table, changelogtag.Columns, sqlgraph.NewFieldSpec(changelogtag.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChangelogTag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, changelogtag.FieldID)
		for _, f := range fields {
			if !changelogtag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != changelogtag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(changelogtag.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(changelogtag.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(changelogtag.FieldColor, field.TypeString, value)
	}
	if _u.mutation.ColorCleared() {
		_spec.ClearField(changelogtag.FieldColor, field.TypeString)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   changelogtag.GroupTable,
			Columns: []string{changelogtag.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   changelogtag.GroupTable,
			Columns: []string{changelogtag.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangelogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   changelogtag.ChangelogsTable,
			Columns: []string{changelogtag.ChangelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changelog.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChangelogsIDs(); len(nodes) > 0 && !_u.mutation.ChangelogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   changelogtag.ChangelogsTable,
			Columns: []string{changelogtag.ChangelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changelog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangelogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   changelogtag.ChangelogsTable,
			Columns: []string{changelogtag.ChangelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changelog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChangelogTag{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{changelogtag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
