// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/changelog"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/changelogtag"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
)

// ChangelogTagCreate is the builder for creating a ChangelogTag entity.
type ChangelogTagCreate struct {
	config
	mutation *ChangelogTagMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChangelogTagCreate) SetCreatedAt(v time.Time) *ChangelogTagCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChangelogTagCreate) SetNillableCreatedAt(v *time.Time) *ChangelogTagCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChangelogTagCreate) SetUpdatedAt(v time.Time) *ChangelogTagCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChangelogTagCreate) SetNillableUpdatedAt(v *time.Time) *ChangelogTagCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ChangelogTagCreate) SetName(v string) *ChangelogTagCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetColor sets the "color" field.
func (_c *ChangelogTagCreate) SetColor(v string) *ChangelogTagCreate {
	_c.mutation.SetColor(v)
	return _c
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_c *ChangelogTagCreate) SetNillableColor(v *string) *ChangelogTagCreate {
	if v != nil {
		_c.SetColor(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ChangelogTagCreate) SetID(v uuid.UUID) *ChangelogTagCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ChangelogTagCreate) SetNillableID(v *uuid.UUID) *ChangelogTagCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGroupID sets the "group" edge to the Group entity by ID.
func (_c *ChangelogTagCreate) SetGroupID(id uuid.UUID) *ChangelogTagCreate {
	_c.mutation.SetGroupID(id)
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *ChangelogTagCreate) SetGroup(v *Group) *ChangelogTagCreate {
	return _c.SetGroupID(v.ID)
}

// AddChangelogIDs adds the "changelogs" edge to the Changelog entity by IDs.
func (_c *ChangelogTagCreate) AddChangelogIDs(ids ...uuid.UUID) *ChangelogTagCreate {
	_c.mutation.AddChangelogIDs(ids...)
	return _c
}

// AddChangelogs adds the "changelogs" edges to the Changelog entity.
func (_c *ChangelogTagCreate) AddChangelogs(v ...*Changelog) *ChangelogTagCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChangelogIDs(ids...)
}

// Mutation returns the ChangelogTagMutation object of the builder.
func (_c *ChangelogTagCreate) Mutation() *ChangelogTagMutation {
	return _c.mutation
}

// Save creates the ChangelogTag in the database.
func (_c *ChangelogTagCreate) Save(ctx context.Context) (*ChangelogTag, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChangelogTagCreate) SaveX(ctx context.Context) *ChangelogTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChangelogTagCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChangelogTagCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChangelogTagCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := changelogtag.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := changelogtag.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Color(); !ok {
		v := changelogtag.DefaultColor
		_c.mutation.SetColor(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := changelogtag.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChangelogTagCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChangelogTag.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChangelogTag.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ChangelogTag.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := changelogtag.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ChangelogTag.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Color(); ok {
		if err := changelogtag.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "ChangelogTag.color": %w`, err)}
		}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "ChangelogTag.group"`)}
	}
	return nil
}

func (_c *ChangelogTagCreate) sqlSave(ctx context.Context) (*ChangelogTag, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChangelogTagCreate) createSpec() (*ChangelogTag, *sqlgraph.CreateSpec) {
	var (
		_node = &ChangelogTag{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(changelogtag.Table, sqlgraph.NewFieldSpec(changelogtag.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(changelogtag.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(changelogtag.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(changelogtag.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Color(); ok {
		_spec.SetField(changelogtag.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   changelogtag.GroupTable,
			Columns: []string{changelogtag.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.group_changelog_tags = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChangelogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   changelogtag.ChangelogsTable,
			Columns: []string{changelogtag.ChangelogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changelog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChangelogTagCreateBulk is the builder for creating many ChangelogTag entities in bulk.
type ChangelogTagCreateBulk struct {
	config
	err      error
	builders []*ChangelogTagCreate
}

// Save creates the ChangelogTag entities in the database.
func (_c *ChangelogTagCreateBulk) Save(ctx context.Context) ([]*ChangelogTag, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChangelogTag, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChangelogTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChangelogTagCreateBulk) SaveX(ctx context.Context) []*ChangelogTag {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChangelogTagCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChangelogTagCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
