// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/changelogtag"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ChangelogTagDelete is the builder for deleting a ChangelogTag entity.
type ChangelogTagDelete struct {
	config
	hooks    []Hook
	mutation *ChangelogTagMutation
}

// Where appends a list predicates to the ChangelogTagDelete builder.
func (_d *ChangelogTagDelete) Where(ps ...predicate.ChangelogTag) *ChangelogTagDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChangelogTagDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChangelogTagDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChangelogTagDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(changelogtag.Table, sqlgraph.NewFieldSpec(changelogtag.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChangelogTagDeleteOne is the builder for deleting a single ChangelogTag entity.
type ChangelogTagDeleteOne struct {
	_d *ChangelogTagDelete
}

// Where appends a list predicates to the ChangelogTagDelete builder.
func (_d *ChangelogTagDeleteOne) Where(ps ...predicate.ChangelogTag) *ChangelogTagDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChangelogTagDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{changelogtag.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChangelogTagDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
